### ISSUE TITLE
Is there an option to trim the barcode after the split?

### ISSUE THREAD

**Issue by rgranit** [jfjlaros/demultiplex#10]
Hi, Is there an option to trim the barcode after the split? if not, is there an option to add this feature?

**Comment by jfjlaros** [comment]
This was intentionally left out because it would duplicate functionality already present in tools like:

- [FASTX-Toolkit](http://hannonlab.cshl.edu/fastx_toolkit/).
- [fastp](https://github.com/OpenGene/fastp).
- [Fastools](https://fastools.readthedocs.io/en/latest/).

I recommend using one of the tools mentioned above.

**Comment by rgranit** [comment]
Thanks @jfjlaros, makes sense..
