### ISSUE TITLE
Paired end support for match.

### ISSUE THREAD

**Issue by Averstic** [jfjlaros/demultiplex#20]
Hi, 

Really like your tool, super useful, but I was just wondering if it would be at all possible to add paired-end support for the match functionality, or if you could point out how to alter the code to do this.

Thanks

**Comment by jfjlaros** [comment]
It should not be too hard to implement, as long as all barcodes are in the same file (otherwise a two step demultiplexing should be done as explained [here](https://demultiplex.readthedocs.io/en/latest/usage.html#multiple-barcodes)).

I am just wondering about the use case though. The `match` subcommand is for handling barcodes at unknown locations in the read. This practice is usually employed in long read sequencing experiments, which usually do not have paired ends. In Illumina sequencing on the other hand, I have never encountered an experiment where the exact location of the barcode is unknown.

**Comment by jfjlaros** [comment]
I made the necessary changes. Perhaps you can give it a try?
