### ISSUE TITLE
Does this tool works for Cell hashing data generated for cell ranger multi?

### ISSUE THREAD

**Issue by bhuwankhatri11** [jfjlaros/demultiplex#31]
I have a multiplexed scFFPE data for cell ranger multi. Can I use demultiplex tool to demux these data?
I have tried but using following setting and the program is running for a week almost and it is still not done yet. So I wonder if it is doing it correctly.

My command to run the program is-
`demultiplex match -m 3 -d samplesheet_re.tsv sample1_S1_R1_001.fastq.gz sample1_S1_R2_001.fastq.gz`

My barcode file looks like this-
```
BC001	ACTTTAGG	ACTTTAGG
BC001	CTTTAGGC	ACTTTAGG
BC001	CGAGGGTA	ACTTTAGG
BC001	GAGGGTAC	ACTTTAGG
BC001	GACACTAC	ACTTTAGG
BC001	ACACTACC	ACTTTAGG
BC001	TTGCACCT	ACTTTAGG
BC001	TGCACCTC	ACTTTAGG
BC002	AACGGGAA	AACGGGAA
BC002	ACGGGAAC	AACGGGAA
BC002	CGAATTGC	AACGGGAA
BC002	GAATTGCC	AACGGGAA
BC002	GTTCCATT	AACGGGAA
BC002	TTCCATTC	AACGGGAA
BC002	TCGTACCG	AACGGGAA
BC002	CGTACCGC	AACGGGAA
BC003	AGTAGGCT	AGTAGGCT
BC003	GTAGGCTC	AGTAGGCT
BC003	CTGTACGA	AGTAGGCT
BC003	TGTACGAC	AGTAGGCT
BC003	GCACCAAG	AGTAGGCT
BC003	CACCAAGC	AGTAGGCT
BC003	TACGTTTC	AGTAGGCT
BC003	ACGTTTCC	AGTAGGCT
BC004	ATGTTGAC	ATGTTGAC
BC004	TGTTGACC	ATGTTGAC
BC004	CACCAACG	ATGTTGAC
BC004	ACCAACGC	ATGTTGAC
BC004	GCTACCGA	ATGTTGAC
BC004	CTACCGAC	ATGTTGAC
BC004	TGAGGTTT	ATGTTGAC
BC004	GAGGTTTC	ATGTTGAC
BC005	ACAGACCT	ACAGACCT
BC005	CAGACCTC	ACAGACCT
BC005	CGGTCGAA	ACAGACCT
BC005	GGTCGAAC	ACAGACCT
BC005	GTCCTTTC	ACAGACCT
BC005	TCCTTTCC	ACAGACCT
BC005	TATAGAGG	ACAGACCT
BC005	ATAGAGGC	ACAGACCT
```
Thank you for your help!

**Comment by jfjlaros** [comment]
The `match` subcommand is used to search for barcodes at [unknown locations in the read](https://demultiplex.readthedocs.io/en/latest/usage.html#barcodes-at-unknown-locations), which is a time consuming procedure, especially when a relatively large number of mismatches is allowed. This is probably not what you need unless you are working with custom designed experiments using long read sequencing data.

Since you are working with Illumina data (I presume), the barcodes are likely at a *known* location in the header. If this is the case, you should use a [two step procedure](https://demultiplex.readthedocs.io/en/latest/usage.html#multiple-barcodes) to demultiplex your files. You should probably also read the section about [custom selection](https://demultiplex.readthedocs.io/en/latest/usage.html#other-files) of barcodes as it is likely the two barcodes are both in the header, separated by a `+` sign.

Also, for this particular set of barcodes no mismatches can be allowed because some barcodes are too similar. For example, barcodes `TACGTTTC` and `GAGGTTTC` have a Hamming distance of 2, so reads containing particular single letter errors (e.g., `GACGTTTC`) cannot be uniquely assigned to either of them.

**Comment by bhuwankhatri11** [comment]
These are the data generated using Chromium Fixed RNA Profiling Reagent Kits for 10x. I do not think the barcodes are in the header, separated by a + sign of fastq files. You can check this [link](https://cdn.10xgenomics.com/image/upload/v1694503892/support-documents/CG000527_ChromiumFixedRNAProfiling_MultiplexedSamples_UserGuide_Rev_E.pdf). Barcodes are BC001 through BC008. Cellranger does pretty good job in demultiplexing data but for this particular data, I would like to demultiplex using outside tools like demultiplex if it works.

**Comment by jfjlaros** [comment]
If these files are the result the demultiplexing procedure described in the document you referenced (`cellranger mkfastq`), then there is nothing left to demultiplex.

If these files are the result of a standard demultiplexing procedure (`bcl2fastq`), then the barcodes should be present either in the header or in the read, depending on the configuration of the demultiplexing run, but always at fixed locations.

Perhaps you can share the first 10 lines of the first FastQ file so I can have a look?
